// Auto-generated IB question bank — do not edit manually
// Total: 400 questions across 8 categories
// Sources: QBANK 700+ (14 banks), TD Securities Preview, UBS Toughest Questions,
//          adapted questions from _questionBank.js, and original generated questions

const IB_QUESTIONS = [

  // ─── ACCOUNTING (55) ─────────────────────────────────────────────────────────

  // Easy
  {
    id: "ib_001",
    question: "What are the three financial statements?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_002",
    question: "What is EBITDA and why do analysts use it?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_003",
    question: "What is working capital?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_004",
    question: "What is goodwill and how does it arise on the balance sheet?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_005",
    question: "What is the difference between book value and market value? Can a company have a negative book value?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_006",
    question: "What is a deferred tax liability (DTL)?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_007",
    question: "What are the main components of shareholders' equity?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_008",
    question: "What are the key line items on a cash flow statement?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_009",
    question: "What is a net operating loss (NOL) and how does it work?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_010",
    question: "Why is cash subtracted from enterprise value?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_011",
    question: "Why is minority interest added to enterprise value?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_012",
    question: "Why can't you use EV/Net Income or Price/EBITDA as valuation multiples?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_013",
    question: "What is the difference between depreciation and amortization? Give an example of an asset you'd apply each to.",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_014",
    question: "What is accrual-basis accounting and how does it differ from cash-basis accounting?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_015",
    question: "What is COGS and how does it differ from operating expenses?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_016",
    question: "What is the accounting equation, and why must it always balance?",
    category: "Accounting",
    difficulty: "Easy",
  },
  {
    id: "ib_017",
    question: "What is the matching principle in accounting and why does it matter for revenue recognition?",
    category: "Accounting",
    difficulty: "Easy",
  },

  // Medium
  {
    id: "ib_018",
    question: "How are the three financial statements connected to each other?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_019",
    question: "How does a $10 increase in depreciation affect the three financial statements?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_020",
    question: "Walk me through the impact of purchasing $100 of PP&E with cash on all three financial statements.",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_021",
    question: "Walk me through the impact of purchasing inventory and then selling it on the three financial statements.",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_022",
    question: "How does PIK (payment-in-kind) interest affect the three financial statements?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_023",
    question: "How does a $10 write-down of a book asset affect the three financial statements?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_024",
    question: "How does selling an asset for a gain affect the three financial statements?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_025",
    question: "If revenue increases by $10, what is the impact on EBITDA (assume a 40% tax rate)?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_026",
    question: "Which financial statement is most important, and why?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_027",
    question: "How do you calculate free cash flow from net income?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_028",
    question: "Walk me through the bridge from EBITDA to unlevered free cash flow to levered free cash flow.",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_029",
    question: "How do you get from EBITDA to cash flow from operations?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_030",
    question: "Under what circumstances can a company legally pay $0 in taxes?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_031",
    question: "Walk me through the accounting for a $200 million factory acquisition paid entirely in cash.",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_032",
    question: "When a company has excess cash, how does the decision to repay debt vs. buy back shares differ in its impact on the financial statements?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_033",
    question: "In a rising-price environment, how does choosing LIFO vs. FIFO affect a company's tax bill?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_034",
    question: "How does depreciation flow through all three financial statements?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_035",
    question: "What are the main differences between IFRS and US GAAP?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_036",
    question: "Under what conditions can equity value exceed enterprise value?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_037",
    question: "What is deferred revenue and why is it a liability? Walk through a real-world example of how it unwinds over time.",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_038",
    question: "Should stock-based compensation (SBC) be added back when calculating free cash flow? Walk through both sides of the debate.",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_039",
    question: "A company buys back $100 million of its own stock — walk through the impact on all three financial statements.",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_040",
    question: "What is the indirect method for the cash flow statement, and why do we start with net income rather than cash received?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_041",
    question: "What is the difference between an operating lease and a finance lease under ASC 842, and how do they appear differently on the three statements?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_042",
    question: "How does revenue recognition work under ASC 606? Walk through the five-step model with an example.",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_043",
    question: "What is impairment, when is it triggered, and how does it flow through the financial statements?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_044",
    question: "A company reports $50 million in net income but negative $30 million in operating cash flow — walk through the most likely accounting explanations.",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_045",
    question: "A SaaS company has $100 million in revenue but $80 million in deferred revenue on the balance sheet — what does this mean and what does it imply about growth momentum?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_046",
    question: "A company's accounts receivable balance has doubled while revenue grew only 10% — what might this signal and what questions would you ask management?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_047",
    question: "A company's auditor just issued a going concern qualification — what does this mean, what likely triggered it, and what options does the company have?",
    category: "Accounting",
    difficulty: "Medium",
  },
  {
    id: "ib_048",
    question: "A company is growing revenue 20% year-over-year but running out of cash — what are the accounting and working capital explanations?",
    category: "Accounting",
    difficulty: "Medium",
  },

  // Hard
  {
    id: "ib_049",
    question: "Walk me through the full accounting treatment of a PP&E purchase financed with PIK debt, including capitalization, straight-line depreciation, and PIK interest accrual across all three statements.",
    category: "Accounting",
    difficulty: "Hard",
  },
  {
    id: "ib_050",
    question: "A company has had positive EBITDA for 19 consecutive years but goes bankrupt in year 20 — how is that possible?",
    category: "Accounting",
    difficulty: "Hard",
  },
  {
    id: "ib_051",
    question: "A company capitalizes a cost that should have been expensed — walk through the multi-year impact on net income, assets, and cash flow in the current year and in subsequent years.",
    category: "Accounting",
    difficulty: "Hard",
  },
  {
    id: "ib_052",
    question: "How does a sale-leaseback transaction work, why might a company pursue one, and what are the accounting implications under ASC 842?",
    category: "Accounting",
    difficulty: "Hard",
  },
  {
    id: "ib_053",
    question: "Walk through how goodwill impairment is triggered, measured, and flows through the financial statements — and what a large impairment charge implies about the original acquisition.",
    category: "Accounting",
    difficulty: "Hard",
  },
  {
    id: "ib_054",
    question: "What is a variable interest entity (VIE) and why might a company consolidate one even without a majority ownership stake? What are the risks of off-balance-sheet treatment?",
    category: "Accounting",
    difficulty: "Hard",
  },
  {
    id: "ib_055",
    question: "A company has $200 million in deferred tax liabilities from accelerated depreciation for tax purposes — walk through how this arose, why it is classified as a liability, and when it reverses.",
    category: "Accounting",
    difficulty: "Hard",
  },

  // ─── BRAIN TEASERS (35) ──────────────────────────────────────────────────────

  // Easy
  {
    id: "ib_056",
    question: "What is the angle between the minute hand and the hour hand of a clock at 3:15?",
    category: "Brain Teasers",
    difficulty: "Easy",
  },
  {
    id: "ib_057",
    question: "What is 38 squared?",
    category: "Brain Teasers",
    difficulty: "Easy",
  },
  {
    id: "ib_058",
    question: "What is the sum of integers from 1 to 100?",
    category: "Brain Teasers",
    difficulty: "Easy",
  },
  {
    id: "ib_059",
    question: "What is the expected value of a single roll of a standard six-sided die?",
    category: "Brain Teasers",
    difficulty: "Easy",
  },
  {
    id: "ib_060",
    question: "What is the approximate value of the square root of 0.1?",
    category: "Brain Teasers",
    difficulty: "Easy",
  },
  {
    id: "ib_061",
    question: "A bat and a ball cost $1.10 together. The bat costs $1.00 more than the ball. How much does the ball cost?",
    category: "Brain Teasers",
    difficulty: "Easy",
  },
  {
    id: "ib_062",
    question: "You have 12 identical-looking balls and a balance scale. One ball is slightly heavier than the rest. What is the minimum number of weighings needed to identify the heavier ball?",
    category: "Brain Teasers",
    difficulty: "Easy",
  },

  // Medium
  {
    id: "ib_063",
    question: "How many zeros are at the end of 100 factorial (100!)?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_064",
    question: "What is the NPV of receiving $1 at the end of each year for 10 years, discounted at 10%?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_065",
    question: "Lily pads double in size every day and cover an entire pond in 60 days. On what day do they cover half the pond?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_066",
    question: "A snail climbs 3 feet up a 10-foot pole each day but slides back 1 foot each night. How many days does it take to reach the top?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_067",
    question: "You have a drawer full of red and blue socks. What is the minimum number of socks you must pull out in the dark to guarantee a matching pair?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_068",
    question: "How would you measure exactly 4 liters of water using only a 3-liter and a 5-liter container?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_069",
    question: "Estimate how many airplanes are above New York City at any given moment.",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_070",
    question: "Estimate how many trees are in Central Park.",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_071",
    question: "Estimate the total annual value of the tie industry in the United Kingdom.",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_072",
    question: "How many matches are played in total at the Wimbledon Championships in a single year?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_073",
    question: "Estimate how many airplanes land at London Gatwick Airport per day.",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_074",
    question: "Estimate the total volume of beer consumed in the United States during the month of April.",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_075",
    question: "Estimate the number of cigarettes produced in the United States annually.",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_076",
    question: "A 6×6×6 cube is painted on all exterior faces and then cut into 216 unit (1×1×1) cubes. How many of the unit cubes have paint on at least one face?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_077",
    question: "Estimate the number of golf balls that fit in a standard school bus.",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_078",
    question: "A disease affects 1 in 1,000 people. A test for it has a 5% false positive rate and no false negatives. A patient tests positive — what is the probability they actually have the disease?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_079",
    question: "How many piano tuners are there in Chicago?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_080",
    question: "You flip a fair coin until you get heads. You win $2^n where n is the number of flips. How much would you pay to play this game?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_081",
    question: "Estimate the number of gas stations in the United States.",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_082",
    question: "You have three light switches outside a room, one of which controls a light inside. You can only enter the room once. How do you determine which switch controls the light?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },
  {
    id: "ib_083",
    question: "You are in a room with two doors — one leads to freedom, one to death. One guard always lies and one always tells the truth. What single question do you ask to find the door to freedom?",
    category: "Brain Teasers",
    difficulty: "Medium",
  },

  // Hard
  {
    id: "ib_084",
    question: "If you roll two dice repeatedly, what is the probability of rolling a sum of 4 before rolling a sum of 2?",
    category: "Brain Teasers",
    difficulty: "Hard",
  },
  {
    id: "ib_085",
    question: "What is the probability of being dealt a full house in a standard five-card poker hand?",
    category: "Brain Teasers",
    difficulty: "Hard",
  },
  {
    id: "ib_086",
    question: "You are presented with two sealed envelopes, one of which contains twice as much money as the other. You open the first and find $100. Should you switch to the other envelope?",
    category: "Brain Teasers",
    difficulty: "Hard",
  },
  {
    id: "ib_087",
    question: "A 10×10×10 cube is painted on all exterior faces and then the entire outer layer of unit cubes is removed. How many 1×1×1 unit cubes remain?",
    category: "Brain Teasers",
    difficulty: "Hard",
  },
  {
    id: "ib_088",
    question: "A company's revenue and market cap are both $1 billion. Its P/E ratio is 25x, net margin is 8%, and it has $200 million in net debt. Assuming a 30% EBITDA margin, what is its EV/EBITDA?",
    category: "Brain Teasers",
    difficulty: "Hard",
  },
  {
    id: "ib_089",
    question: "If the probability of rain on any given day is 30%, what is the probability that it rains at least once over a 5-day period?",
    category: "Brain Teasers",
    difficulty: "Hard",
  },
  {
    id: "ib_090",
    question: "How many rectangles (including squares) can be formed using the grid lines of a standard 3×3 square grid?",
    category: "Brain Teasers",
    difficulty: "Hard",
  },

  // ─── DCF (50) ────────────────────────────────────────────────────────────────

  // Easy
  {
    id: "ib_091",
    question: "What is a DCF (discounted cash flow) analysis and when is it used?",
    category: "DCF",
    difficulty: "Easy",
  },
  {
    id: "ib_092",
    question: "What is WACC (weighted average cost of capital)?",
    category: "DCF",
    difficulty: "Easy",
  },
  {
    id: "ib_093",
    question: "What is CAPM (Capital Asset Pricing Model) and what is it used for?",
    category: "DCF",
    difficulty: "Easy",
  },
  {
    id: "ib_094",
    question: "What is beta and why does it matter in financial modeling?",
    category: "DCF",
    difficulty: "Easy",
  },
  {
    id: "ib_095",
    question: "What are the two methods for calculating terminal value in a DCF?",
    category: "DCF",
    difficulty: "Easy",
  },
  {
    id: "ib_096",
    question: "What is a sensitivity table in a DCF and which two variables do you typically sensitize?",
    category: "DCF",
    difficulty: "Easy",
  },
  {
    id: "ib_097",
    question: "What is the time value of money and why is it the foundation of a DCF?",
    category: "DCF",
    difficulty: "Easy",
  },

  // Medium
  {
    id: "ib_098",
    question: "Walk me through a DCF analysis from start to finish.",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_099",
    question: "How do you calculate WACC?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_100",
    question: "How do you calculate the cost of equity using CAPM?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_101",
    question: "Why is cost of equity typically higher than cost of debt?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_102",
    question: "What terminal growth rate assumption would you use in a DCF, and why?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_103",
    question: "What is the difference between the Gordon Growth Model and the Exit Multiple Method for calculating terminal value?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_104",
    question: "When would you use the Gordon Growth Model vs. the Exit Multiple Method for terminal value?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_105",
    question: "What are the key assumptions in a DCF and which sensitivities matter most?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_106",
    question: "How does an increase in interest rates affect a DCF valuation?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_107",
    question: "If interest rates rise by 100 basis points, what happens to your DCF valuation?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_108",
    question: "How do taxes factor into a DCF model?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_109",
    question: "What is the impact of higher corporate taxes on a DCF valuation?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_110",
    question: "What are the key value drivers in a DCF model?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_111",
    question: "Which has a greater impact on a DCF valuation: a 1% change in WACC or a 1% change in the revenue growth rate?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_112",
    question: "How do you calculate beta when it is not publicly available?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_113",
    question: "How does reducing a company's leverage ratio affect its cost of equity?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_114",
    question: "How does a change in capital structure affect a company's WACC?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_115",
    question: "If a company has a beta of zero, what does that imply for its WACC?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_116",
    question: "What happens to a company's WACC when it raises additional debt?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_117",
    question: "Compare the WACC of a 100% equity-financed firm vs. one with a 50/50 equity-to-debt capital structure.",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_118",
    question: "What is the difference between an unlevered DCF and a levered DCF?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_119",
    question: "How do you project revenue growth in a DCF model?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_120",
    question: "Given a stock price, shares outstanding, debt balance, beta, risk-free rate, and equity risk premium, walk me through how you would calculate WACC.",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_121",
    question: "Which inputs in the WACC formula are the hardest to estimate, and why?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_122",
    question: "How do you pick a terminal growth rate using the Gordon Growth Model, and what real-world constraints should bound your assumption?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_123",
    question: "How would you check whether a terminal value estimate is reasonable before presenting it to a client?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_124",
    question: "If a company changes its capital structure from 10% to 30% debt, does the unlevered DCF change? Why or why not?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_125",
    question: "How does the choice of discount rate affect how much of a DCF's total value comes from terminal value vs. the forecast period?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_126",
    question: "Walk me through how to calculate unlevered free cash flow (FCFF) starting from EBIT.",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_127",
    question: "Should you add back stock-based compensation (SBC) when calculating free cash flow in a DCF? Walk through the arguments on both sides.",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_128",
    question: "Walk me through how you would build the WACC for an LBO target — which inputs carry the most judgment and why?",
    category: "DCF",
    difficulty: "Medium",
  },
  {
    id: "ib_129",
    question: "How does a dividend discount model (DDM) differ from a DCF, and when would you use one over the other?",
    category: "DCF",
    difficulty: "Medium",
  },

  // Hard
  {
    id: "ib_130",
    question: "How would you build a DCF for a pharmaceutical company whose key drug patent expires in Year 3 of your forecast period?",
    category: "DCF",
    difficulty: "Hard",
  },
  {
    id: "ib_131",
    question: "How would you build a DCF for an early-stage biotech company that has no current revenue?",
    category: "DCF",
    difficulty: "Hard",
  },
  {
    id: "ib_132",
    question: "If a company makes a major factory purchase in Year 4 of your DCF forecast, how does that affect your model?",
    category: "DCF",
    difficulty: "Hard",
  },
  {
    id: "ib_133",
    question: "How does beta vary across upstream, midstream, and downstream energy companies, and why?",
    category: "DCF",
    difficulty: "Hard",
  },
  {
    id: "ib_134",
    question: "Compare the beta profiles of a luxury goods company like Louis Vuitton vs. a value retailer like the Gap. Which has a higher beta and why?",
    category: "DCF",
    difficulty: "Hard",
  },
  {
    id: "ib_135",
    question: "Which has a bigger impact on DCF output: revenue growth dropping from 10% to 5%, or the discount rate dropping from 10% to 5%? Walk through the math.",
    category: "DCF",
    difficulty: "Hard",
  },
  {
    id: "ib_136",
    question: "Walk through the full effect of a corporate tax cut from 35% to 21% on WACC and DCF output.",
    category: "DCF",
    difficulty: "Hard",
  },
  {
    id: "ib_137",
    question: "If you extend a DCF forecast period from 10 years to 20 years, how and why does the valuation output change?",
    category: "DCF",
    difficulty: "Hard",
  },
  {
    id: "ib_138",
    question: "A company's terminal value represents 85% of total DCF output. Your associate says the DCF is unreliable. Do you agree? How do you defend or improve the analysis?",
    category: "DCF",
    difficulty: "Hard",
  },
  {
    id: "ib_139",
    question: "How does a 50bps increase in WACC affect a DCF valuation, and why does terminal value get hit harder than the forecast period cash flows?",
    category: "DCF",
    difficulty: "Hard",
  },
  {
    id: "ib_140",
    question: "How would you build a DCF for an emerging market company differently from one in a developed market? What inputs change and why?",
    category: "DCF",
    difficulty: "Hard",
  },

  // ─── DEBT & CAPITAL STRUCTURE (50) ───────────────────────────────────────────

  // Easy
  {
    id: "ib_141",
    question: "Why is debt typically cheaper than equity as a source of financing?",
    category: "Debt & Capital Structure",
    difficulty: "Easy",
  },
  {
    id: "ib_142",
    question: "What is a convertible bond?",
    category: "Debt & Capital Structure",
    difficulty: "Easy",
  },
  {
    id: "ib_143",
    question: "What is the risk-free rate and how is it typically estimated?",
    category: "Debt & Capital Structure",
    difficulty: "Easy",
  },
  {
    id: "ib_144",
    question: "What is the difference between a call option and a put option?",
    category: "Debt & Capital Structure",
    difficulty: "Easy",
  },
  {
    id: "ib_145",
    question: "What is a credit default swap (CDS)?",
    category: "Debt & Capital Structure",
    difficulty: "Easy",
  },
  {
    id: "ib_146",
    question: "What is the difference between equity capital markets (ECM) and debt capital markets (DCM)?",
    category: "Debt & Capital Structure",
    difficulty: "Easy",
  },
  {
    id: "ib_147",
    question: "What is the yield curve and what does its shape tell you about economic expectations?",
    category: "Debt & Capital Structure",
    difficulty: "Easy",
  },
  {
    id: "ib_148",
    question: "What is the difference between Chapter 7 and Chapter 11 bankruptcy?",
    category: "Debt & Capital Structure",
    difficulty: "Easy",
  },
  {
    id: "ib_149",
    question: "What is short selling and how does it work mechanically? What are the key risks?",
    category: "Debt & Capital Structure",
    difficulty: "Easy",
  },

  // Medium
  {
    id: "ib_150",
    question: "What is high yield debt and how does it differ from investment-grade debt?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_151",
    question: "What are the primary risks of taking on too much leverage?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_152",
    question: "Why can some companies sustain significantly higher levels of leverage than others?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_153",
    question: "When can selling an asset actually increase a company's leverage ratio?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_154",
    question: "What is bond duration and why does it matter to fixed income investors?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_155",
    question: "Why do zero-coupon bonds have longer duration than par coupon bonds of the same maturity?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_156",
    question: "What are the primary risks of owning a bond?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_157",
    question: "How would you hedge the interest rate risk on a bond portfolio?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_158",
    question: "What credit rating threshold qualifies a bond as high yield?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_159",
    question: "When advising a company on a bond issuance, how would you decide whether to denominate it in USD, EUR, or GBP?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_160",
    question: "Why do long-term bonds typically offer higher yields than short-term bonds?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_161",
    question: "What happens to bank profitability in a negative interest rate environment?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_162",
    question: "What is Basel III and why does it matter to the banking sector?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_163",
    question: "What is Value at Risk (VaR) and what are its key advantages and disadvantages?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_164",
    question: "If you double a company's leverage, what happens to its equity value, cost of capital, and overall risk?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_165",
    question: "As CFO of a profitable company with stable, recurring cash flows, when would you choose to issue debt vs. equity to fund growth?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_166",
    question: "How would you advise a growing company on whether to initiate its first dividend payment?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_167",
    question: "Would you rather receive $100 today or $1 per year growing at 5% in perpetuity? At what discount rate are they equivalent?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_168",
    question: "What is a forward FX contract and how is it used to hedge currency risk?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_169",
    question: "What factors affect the pricing of a residential mortgage-backed security?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_170",
    question: "How are preferred shares and preferred dividends treated in financial analysis and valuation?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_171",
    question: "What is the Debt Service Coverage Ratio (DSCR) and how do lenders use it?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_172",
    question: "Walk me through a debt issuance from initial mandate to closing.",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_173",
    question: "What is the difference between coupon rate, current yield, and yield to maturity?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_174",
    question: "How do you value a bond? Walk through the mechanics.",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_175",
    question: "What is the difference between stressed, distressed, and bankrupt companies?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_176",
    question: "What options does a distressed company have — refinancing, asset sales, out-of-court restructuring, or filing for bankruptcy? Walk through the trade-offs.",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_177",
    question: "What is DIP (debtor-in-possession) financing and why do companies seek it during Chapter 11?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_178",
    question: "What is a repo agreement and why do banks use it for short-term funding?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_179",
    question: "Should operating leases be added to enterprise value? Walk through the argument.",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_180",
    question: "What is put-call parity? Write the formula and walk through the logic of why it must hold.",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_181",
    question: "What is convexity and why does a bond with higher convexity outperform in volatile rate environments?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_182",
    question: "What is the difference between maintenance covenants and incurrence covenants, and why has the leveraged loan market shifted toward cov-lite structures?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },
  {
    id: "ib_183",
    question: "What is quantitative easing and what are the risks of unwinding it?",
    category: "Debt & Capital Structure",
    difficulty: "Medium",
  },

  // Hard
  {
    id: "ib_184",
    question: "Walk me through how you would structure the debt financing for a leveraged buyout, including the key instruments you would use and how you would size each tranche.",
    category: "Debt & Capital Structure",
    difficulty: "Hard",
  },
  {
    id: "ib_185",
    question: "Walk me through how an interest rate swap works. If you're receiving fixed and paying floating, are you expressing a bullish or bearish view on interest rates, and why?",
    category: "Debt & Capital Structure",
    difficulty: "Hard",
  },
  {
    id: "ib_186",
    question: "A company has $500 million in excess cash — walk through the decision between a share buyback, a special dividend, and debt paydown. What factors drive each choice and what are the tax and signaling implications?",
    category: "Debt & Capital Structure",
    difficulty: "Hard",
  },
  {
    id: "ib_187",
    question: "Walk me through a leveraged recapitalization — why would a company pursue one, what's the accounting treatment, and how does it affect equity value and risk?",
    category: "Debt & Capital Structure",
    difficulty: "Hard",
  },
  {
    id: "ib_188",
    question: "What is negative convexity in a callable bond and in a mortgage-backed security? How does it affect the investor's risk profile as rates fall?",
    category: "Debt & Capital Structure",
    difficulty: "Hard",
  },
  {
    id: "ib_189",
    question: "What causes swap spreads to widen? Walk through the relationship between credit risk, interest rate expectations, and the spread between fixed-rate swaps and Treasuries.",
    category: "Debt & Capital Structure",
    difficulty: "Hard",
  },
  {
    id: "ib_190",
    question: "Compare the risk/return profile of a 5-year investment-grade corporate bond vs. a 5-year high-yield bond vs. a leveraged loan. Which would you recommend to a client with a 5-year horizon and moderate risk tolerance?",
    category: "Debt & Capital Structure",
    difficulty: "Hard",
  },

  // ─── LBO (35) ────────────────────────────────────────────────────────────────

  // Easy
  {
    id: "ib_191",
    question: "What is a leveraged buyout (LBO)?",
    category: "LBO",
    difficulty: "Easy",
  },
  {
    id: "ib_192",
    question: "What is IRR (internal rate of return) and how is it used to evaluate LBO investments?",
    category: "LBO",
    difficulty: "Easy",
  },
  {
    id: "ib_193",
    question: "What is carried interest and how is it taxed differently from a salary?",
    category: "LBO",
    difficulty: "Easy",
  },
  {
    id: "ib_194",
    question: "What is a dividend recapitalization and why would a private equity firm pursue one mid-hold?",
    category: "LBO",
    difficulty: "Easy",
  },
  {
    id: "ib_195",
    question: "What is the difference between MOIC and IRR, and when does each matter more as a performance metric?",
    category: "LBO",
    difficulty: "Easy",
  },

  // Medium
  {
    id: "ib_196",
    question: "What characteristics make a company a good LBO candidate?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_197",
    question: "What are the primary ways in which a financial sponsor creates value in an LBO?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_198",
    question: "Walk me through how you would build an LBO model.",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_199",
    question: "In an LBO, what has a greater impact on sponsor returns: paying down $1 of debt or increasing EBITDA by $1?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_200",
    question: "In an LBO, what has a greater impact on returns: growing EBITDA by $10 million or cutting CapEx by $10 million?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_201",
    question: "What is unlevered IRR and how does it differ from levered IRR in an LBO context?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_202",
    question: "How does an increase in days payable outstanding (DPO) affect IRR in an LBO?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_203",
    question: "How do bolt-on acquisitions affect IRR in a private equity portfolio company?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_204",
    question: "Beyond multiple expansion and debt paydown, how can a financial sponsor boost returns in an LBO?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_205",
    question: "How does an LBO model function as a floor valuation methodology for a target company?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_206",
    question: "How would you approach modeling an LBO of an upstream oil and gas company?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_207",
    question: "How do circular references arise in an LBO model and how do you resolve them?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_208",
    question: "How does the level of leverage affect the comparison between levered and unlevered valuations?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_209",
    question: "How do you determine the appropriate amount of debt to put on a company in an LBO?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_210",
    question: "How do rising interest rates affect returns in a leveraged buyout?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_211",
    question: "What makes a technology company an attractive LBO candidate, and what are the key risks?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_212",
    question: "Is a 10% IRR attractive in an LBO context? What factors determine whether it is sufficient?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_213",
    question: "What is a quality of earnings (QoE) report and why is it one of the most critical workstreams in LBO due diligence?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_214",
    question: "What are EBITDA add-backs and what separates a legitimate add-back from an aggressive one?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_215",
    question: "How does a roll-up strategy affect LBO returns? Walk through the multiple expansion math and the risks that roll-ups consistently underestimate.",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_216",
    question: "Walk me through the key considerations in structuring a take-private transaction at a 30% premium to the target's 30-day VWAP.",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_217",
    question: "A PE fund is in year 8 of a 10-year life with three assets still unsold — what options does the GP have and what are the trade-offs for LPs in each path?",
    category: "LBO",
    difficulty: "Medium",
  },
  {
    id: "ib_218",
    question: "How does debt paydown velocity affect IRR differently from MOIC? Give an example where high MOIC does not translate to high IRR.",
    category: "LBO",
    difficulty: "Medium",
  },

  // Hard
  {
    id: "ib_219",
    question: "Construct a scenario in which a company with 19 consecutive years of positive EBITDA declares bankruptcy in year 20 due to its LBO capital structure.",
    category: "LBO",
    difficulty: "Hard",
  },
  {
    id: "ib_220",
    question: "For the same company, when would a DCF imply a higher valuation than an LBO analysis, and when would the LBO imply a higher value?",
    category: "LBO",
    difficulty: "Hard",
  },
  {
    id: "ib_221",
    question: "A PE firm buys a company at 12x EBITDA with 5x Debt/EBITDA leverage. EBITDA doubles in 5 years and no debt is repaid. What exit multiple is needed to achieve a 25% IRR?",
    category: "LBO",
    difficulty: "Hard",
  },
  {
    id: "ib_222",
    question: "A PE firm acquires a company at 10x EBITDA with 6x Debt/EBITDA leverage. EBITDA grows from $100M to $150M over 5 years and $300M of debt is repaid. What exit multiple is needed for a 25% IRR?",
    category: "LBO",
    difficulty: "Hard",
  },
  {
    id: "ib_223",
    question: "A distressed company with $100M EBITDA is sold at 3x EV/EBITDA. It has a $100M revolver, $300M term loan, and $200M in subordinated notes. What are the recovery percentages for each tranche?",
    category: "LBO",
    difficulty: "Hard",
  },
  {
    id: "ib_224",
    question: "A portfolio company is approaching a 5.5x net leverage covenant and EBITDA is declining — walk through all options the sponsor has and how you would model each.",
    category: "LBO",
    difficulty: "Hard",
  },
  {
    id: "ib_225",
    question: "You're in a competitive auction at 12x EBITDA and need 20%+ IRR to clear the investment committee. What creative structuring options do you explore to make the deal work?",
    category: "LBO",
    difficulty: "Hard",
  },

  // ─── M&A (45) ────────────────────────────────────────────────────────────────

  // Easy
  {
    id: "ib_226",
    question: "What is accretion vs. dilution in the context of M&A transactions?",
    category: "M&A",
    difficulty: "Easy",
  },
  {
    id: "ib_227",
    question: "What is goodwill in an acquisition, and how is it calculated?",
    category: "M&A",
    difficulty: "Easy",
  },
  {
    id: "ib_228",
    question: "What are synergies in M&A, and what are the two main types?",
    category: "M&A",
    difficulty: "Easy",
  },
  {
    id: "ib_229",
    question: "What is the difference between a stock acquisition and a cash acquisition?",
    category: "M&A",
    difficulty: "Easy",
  },
  {
    id: "ib_230",
    question: "Walk me through a sell-side M&A process from mandate to close.",
    category: "M&A",
    difficulty: "Easy",
  },
  {
    id: "ib_231",
    question: "Walk me through a buy-side M&A process from deal sourcing to close.",
    category: "M&A",
    difficulty: "Easy",
  },
  {
    id: "ib_232",
    question: "What is in a pitch book and what does each major section accomplish?",
    category: "M&A",
    difficulty: "Easy",
  },

  // Medium
  {
    id: "ib_233",
    question: "If a company trading at 10x P/E acquires a company trading at 12x P/E in an all-stock deal, is the deal accretive or dilutive? Why?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_234",
    question: "If a company trading at 10x P/E acquires a company trading at 5x P/E in an all-stock deal, is the deal accretive or dilutive? Why?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_235",
    question: "How does using a mix of cash and stock financing vs. an all-stock deal affect accretion/dilution?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_236",
    question: "Beyond accretion/dilution, what non-financial factors are critical in evaluating whether an M&A deal makes strategic sense?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_237",
    question: "Why might an acquirer be willing to pay a significant premium over a target's current market price?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_238",
    question: "Walk me through how you would build a merger model.",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_239",
    question: "Why might the management of an acquiring company prefer to use stock rather than cash to fund an acquisition?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_240",
    question: "How does foreign exchange rate movement affect the economics of a cross-border M&A deal?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_241",
    question: "What does it typically signal when the acquirer's stock price drops sharply after an acquisition announcement?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_242",
    question: "What does it mean when a deal spread is wide, indicating investor skepticism about a deal closing?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_243",
    question: "Two companies, each with $50 million in revenue, merge and the combined entity reports $120 million in revenue. How do you explain the $20 million difference?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_244",
    question: "Two companies have the same EV/EBITDA multiple but different leverage — how does that affect their relative P/E multiples?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_245",
    question: "How do you determine how much debt capacity an acquirer has to finance an M&A transaction?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_246",
    question: "What are the most common strategic rationales behind M&A activity?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_247",
    question: "Why would a company choose to acquire rather than build the same capability organically?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_248",
    question: "What are the key advantages and disadvantages of a company going public vs. remaining private?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_249",
    question: "For a cross-border acquisition where the seller is a tax-sensitive founder, would you recommend a stock or cash deal, and why?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_250",
    question: "How do you calculate accretion/dilution on a price-to-cash-flow (P/CF) basis in an oil and gas deal?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_251",
    question: "In a dilutive all-stock deal, how many dollars of synergies are needed to break even on an EPS basis?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_252",
    question: "What key assumptions do you need to make before you can determine whether a deal will be accretive or dilutive?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_253",
    question: "How does an M&A deal create or destroy value? Walk through the key drivers that determine which outcome results.",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_254",
    question: "Walk me through how you would advise a client who has just received an unsolicited bid at a 20% premium to their current stock price.",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_255",
    question: "A strategic acquirer you're advising learns a financial sponsor is also bidding in the same process — how does that change the auction dynamics and your advice?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_256",
    question: "How do you advise a founder on whether to sell to a strategic acquirer today vs. pursuing an IPO in two to three years?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_257",
    question: "What is the difference between a tender offer and a merger? When would a buyer choose each structure?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_258",
    question: "What are common takeover defenses and what is a poison pill? When are they effective?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_259",
    question: "What is the difference between a carve-out, a spinoff, and a split-off?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_260",
    question: "What is a fairness opinion and when is the board of directors typically required to obtain one?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_261",
    question: "What is a go-shop provision in an M&A agreement and why do sellers sometimes negotiate for one?",
    category: "M&A",
    difficulty: "Medium",
  },
  {
    id: "ib_262",
    question: "What is a reverse termination fee and when does it apply?",
    category: "M&A",
    difficulty: "Medium",
  },

  // Hard
  {
    id: "ib_263",
    question: "Walk me through the purchase price allocation (PPA) process in an M&A transaction, including the identification and step-up of intangibles, deferred tax liabilities, and the tax implications of an asset sale vs. a stock sale.",
    category: "M&A",
    difficulty: "Hard",
  },
  {
    id: "ib_264",
    question: "Walk me through an accretion/dilution model for a $2 billion all-stock acquisition — what are the key line items and what determines whether the deal is accretive in year one?",
    category: "M&A",
    difficulty: "Hard",
  },
  {
    id: "ib_265",
    question: "A company's stock drops 15% on the day it announces a large acquisition at a 40% premium. Walk through the possible explanations and how you would advise the CEO.",
    category: "M&A",
    difficulty: "Hard",
  },
  {
    id: "ib_266",
    question: "Why can a strategic acquirer justify paying more for a target than a financial sponsor? Walk through the structural reasons the IRR math works differently for each buyer type.",
    category: "M&A",
    difficulty: "Hard",
  },
  {
    id: "ib_267",
    question: "Make the case for why a large conglomerate should break up its business units rather than continue operating as a combined entity. What conditions make sum-of-the-parts value creation compelling?",
    category: "M&A",
    difficulty: "Hard",
  },
  {
    id: "ib_268",
    question: "You are running an M&A process and the leading bidder submits a revised offer 15% below their initial indication. The seller is furious. Walk through how you would manage the situation.",
    category: "M&A",
    difficulty: "Hard",
  },

  // ─── MARKETS (30) ────────────────────────────────────────────────────────────

  // Easy
  {
    id: "ib_269",
    question: "In general terms, how do changes in interest rates affect equity valuations?",
    category: "Markets",
    difficulty: "Easy",
  },
  {
    id: "ib_270",
    question: "What is the current shape of the yield curve and what does it imply for the economy?",
    category: "Markets",
    difficulty: "Easy",
  },
  {
    id: "ib_271",
    question: "What is the difference between systematic risk and idiosyncratic risk, and why does only systematic risk earn a return premium?",
    category: "Markets",
    difficulty: "Easy",
  },
  {
    id: "ib_272",
    question: "What is the bid-ask spread and why does it widen during periods of market stress?",
    category: "Markets",
    difficulty: "Easy",
  },

  // Medium
  {
    id: "ib_273",
    question: "Give me a brief overview of where equity markets stand today.",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_274",
    question: "Pitch me a stock you would buy today — walk me through your investment thesis.",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_275",
    question: "How would the broader macroeconomic environment affect a specific technology company you follow?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_276",
    question: "What are the current trends in M&A activity globally or in a sector you follow?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_277",
    question: "How do interest rate changes affect valuations differently across different sectors?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_278",
    question: "What is the relationship between interest rates and equity prices?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_279",
    question: "For a company, is it better to increase revenue through higher unit prices or higher unit volumes?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_280",
    question: "What sector or industry are you currently following, and what is your bullish or bearish view?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_281",
    question: "How would a major global supply shock affect Canadian oil prices?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_282",
    question: "Should the United States join OPEC? Make the case for and against.",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_283",
    question: "Why might two oil and gas companies with the same BOE per day production trade at very different EV/BOE multiples?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_284",
    question: "What are the main categories of oil and gas companies by their position in the value chain?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_285",
    question: "What is your outlook on the oil and gas sector over the next 5 to 10 years?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_286",
    question: "Two agricultural companies operate in different geographic regions — how would you compare their costs of capital?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_287",
    question: "What are the major trends in healthcare that a long-term investor should be aware of?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_288",
    question: "Pitch me a stock in the energy sector — walk me through your investment thesis.",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_289",
    question: "What valuation multiple is most appropriate for an oil and gas E&P company and why?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_290",
    question: "How does the broader macroeconomic environment affect a specific stock in your investment universe?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_291",
    question: "If interest rates rise 100 basis points, what happens to bond prices, equity valuations, and the currency? Walk through the transmission mechanism.",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_292",
    question: "What is quantitative easing and how does it affect equity and bond markets?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_293",
    question: "The Fed cuts rates 50bps when the market was pricing only 25bps — walk through the immediate moves you would expect across rates, equities, credit, and FX.",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_294",
    question: "A company's stock drops 10% after reporting earnings down 30% year-over-year. What are the possible explanations?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_295",
    question: "If you had $1 million to invest today, how would you allocate it across asset classes and why?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_296",
    question: "What is the VIX and what does it tell you about market pricing of tail risk?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_297",
    question: "What is the carry trade and how does it work? What causes carry trades to unwind violently?",
    category: "Markets",
    difficulty: "Medium",
  },
  {
    id: "ib_298",
    question: "What is the difference between a futures contract and a forward contract, and when would you use each?",
    category: "Markets",
    difficulty: "Medium",
  },

  // ─── VALUATION (100) ─────────────────────────────────────────────────────────

  // Easy
  {
    id: "ib_299",
    question: "What are the three main valuation methodologies used in investment banking?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_300",
    question: "What is enterprise value and how does it differ from equity value?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_301",
    question: "What is comparable company analysis (trading comps)?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_302",
    question: "What are precedent transactions?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_303",
    question: "What is EV/EBITDA and why is it one of the most widely used valuation multiples?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_304",
    question: "What is the difference between forward and trailing multiples, and when would you use each?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_305",
    question: "What is the dividend discount model (DDM)?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_306",
    question: "What is a football field chart and why do bankers use it instead of quoting a single point estimate?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_307",
    question: "What is the difference between intrinsic value and market value? When do the two diverge significantly?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_308",
    question: "What does a high EV/Revenue multiple tell you about market expectations for a business?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_309",
    question: "Why does a DCF often produce a wide valuation range rather than a single precise number?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_310",
    question: "What is the difference between LTM, NTM, and forward multiples, and when would you prefer each?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_311",
    question: "What multiple would you use for a mature manufacturing company vs. an early-stage SaaS company losing money, and why?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_312",
    question: "Why do enterprise value multiples use pre-debt metrics like EBITDA, while equity value multiples use post-debt metrics like net income?",
    category: "Valuation",
    difficulty: "Easy",
  },
  {
    id: "ib_313",
    question: "What is the fundamental difference between how a strategic buyer and a financial buyer value the same acquisition target?",
    category: "Valuation",
    difficulty: "Easy",
  },

  // Medium
  {
    id: "ib_314",
    question: "Walk me through the pros and cons of each of the three main valuation methodologies.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_315",
    question: "Walk me through the formula for enterprise value.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_316",
    question: "Walk me through a comparable company analysis from start to finish.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_317",
    question: "Walk me through a precedent transaction analysis.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_318",
    question: "When would you use cash-flow multiples (EV/EBITDA) vs. earnings multiples (P/E)?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_319",
    question: "What types of companies would tend to have net income close to EBITDA?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_320",
    question: "How do you translate a comparable company multiple into an implied share price for the target?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_321",
    question: "What criteria do you use to select truly comparable companies in a comps analysis?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_322",
    question: "What are the three most important factors to analyze when selecting precedent transactions?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_323",
    question: "Which valuation methodology typically yields the highest valuation and which the lowest, and why?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_324",
    question: "How do you value a company with negative EBIT?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_325",
    question: "If you had to pick just one valuation method for a mature industrial company, which would you choose and why?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_326",
    question: "How would you value a company that has negative earnings but strong, growing cash flows?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_327",
    question: "How do you bridge from enterprise value to equity value per share?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_328",
    question: "What are the pros and cons of using EV/EBITDA vs. P/E as a valuation multiple?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_329",
    question: "When would you use EV/EBITDA vs. EV/EBIT as your primary valuation multiple?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_330",
    question: "When would you use EV/Revenue vs. EV/EBITDA as your primary multiple?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_331",
    question: "Why might two companies with virtually identical financials trade at very different multiples?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_332",
    question: "Explain how the treasury stock method works for calculating diluted share count.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_333",
    question: "Apply the treasury stock method: a company has 1,000 shares outstanding, 100 options with a $10 strike price, and a current stock price of $15. What is the diluted share count?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_334",
    question: "Are convertible bonds included in the calculation of enterprise value?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_335",
    question: "How does enterprise value change when a company issues new debt to fund operations?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_336",
    question: "If a company discovers an unexpected $100 million in cash, how does that affect its enterprise value and equity value?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_337",
    question: "What is a spinoff and why might a company pursue one?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_338",
    question: "Walk me through the IPO process from start to finish.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_339",
    question: "What are the key advantages and disadvantages of going public via an IPO?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_340",
    question: "How do you evaluate whether an IPO is fairly priced at the time of launch?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_341",
    question: "How does valuing a bank or financial institution differ from valuing a non-financial company?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_342",
    question: "What multiples are most commonly used to value banks and financial institutions?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_343",
    question: "How would you value a medSpa or aesthetic services business?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_344",
    question: "Two companies have identical EBITDA and revenue but trade at different multiples — what explains the difference?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_345",
    question: "How would a strategic acquirer's willingness to pay differ from a private equity buyer's for the same asset?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_346",
    question: "Why would a $2 billion market cap company in a given business have a different cost of capital than a $500 million company in the exact same business?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_347",
    question: "How would you value an apple tree?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_348",
    question: "A company has $200 million in senior debt and $200 million in high yield debt and trades at 5x EV/EBITDA. What is the implied market price of the high yield debt?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_349",
    question: "If a company's EV/EBITDA multiple is 10x and its EV/Revenue multiple is 2x, what is the implied EBITDA margin?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_350",
    question: "If a company's enterprise value is $100 million and it has $400 million of debt outstanding, what is its equity value?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_351",
    question: "Why do precedent transaction multiples typically come in higher than trading comp multiples?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_352",
    question: "How does taking on additional debt affect a company's valuation multiples?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_353",
    question: "A company has Debt/Equity of 1x and Debt/EBITDA of 5x. What is its implied EV/EBITDA multiple?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_354",
    question: "Walk me through the six steps to build a trading comps analysis, from peer group selection to deriving implied value.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_355",
    question: "What multiple would you use to value a REIT? A bank? A pre-revenue biotech? Walk through the reasoning for each.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_356",
    question: "How do you handle a thin comparable transactions set with only three relevant deals in the past 10 years?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_357",
    question: "How do you decide which comps to weight more heavily when the peer group range spans from 6x to 14x EV/EBITDA?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_358",
    question: "What is a control premium and when should you apply it? How does it affect the gap between a trading comps valuation and a take-private bid?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_359",
    question: "A company has $200M EBITDA, $50M in annual restructuring charges, and $30M in stock-based compensation. Walk through what you include or exclude in adjusted EBITDA and why.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_360",
    question: "What is a liquidation valuation and when would you use it?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_361",
    question: "Walk me through how to get from a DCF-derived enterprise value to an implied price per share, including all required bridge adjustments.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_362",
    question: "Two identical companies — same earnings, growth, leverage, and risk. Company A trades at 15x P/E, Company B at 10x P/E. Which would you buy and why?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_363",
    question: "A company has $50M in reported EBITDA but diligence reveals $15M of one-time items management included in the base. How do you adjust the valuation and what do you tell the board?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_364",
    question: "A target you're valuing just settled a major lawsuit for $300M — how does this affect your adjusted EBITDA, your comps analysis, and the bridge to equity value?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_365",
    question: "A target company has a large pension liability that does not appear prominently on the income statement — how would you factor it into your enterprise value bridge and DCF?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_366",
    question: "What is the Rule of 40 for SaaS companies and how does it factor into EV/Revenue multiples?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_367",
    question: "Would you rather buy a company at 8x EBITDA with flat growth or one at 15x EBITDA growing 20% annually? Make the case and walk through the math.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_368",
    question: "How do you sensitize a DCF? Walk me through building a two-variable sensitivity table and which inputs you would pick.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_369",
    question: "You're running comps on a healthcare company and two of your five comparables just received FDA approval, dramatically inflating their multiples. How do you handle this?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_370",
    question: "A $500M EBITDA healthcare company vs. a $500M EBITDA industrials company — which is worth more and why?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_371",
    question: "What is a sum-of-the-parts (SOTP) valuation, when is it appropriate to use, and what is the conglomerate discount?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_372",
    question: "How do you account for leverage dispersion across a comp set — why can't you just use the median multiple when leverage ratios range from 0x to 4x?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_373",
    question: "What does the market imply about a company's growth prospects when it trades at a high EV/EBITDA but a relatively low EV/Revenue?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_374",
    question: "How does the step-up in basis from an acquisition affect the acquirer's future depreciation and amortization, and why does this create a tax shield?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_375",
    question: "What is the difference between equity value and equity value attributable to common shareholders, and why does the distinction matter in valuation?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_376",
    question: "Why do you value a public company if it already has a market cap that reflects what investors are willing to pay?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_377",
    question: "If two otherwise identical companies have different capital structures, should they have the same enterprise value? Walk through your reasoning.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_378",
    question: "What does EV/EBITDA miss for capital-intensive businesses, and which metric do practitioners substitute?",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_379",
    question: "Make the case for why a DCF is superior to trading comps when valuing a high-growth company with negative EBITDA.",
    category: "Valuation",
    difficulty: "Medium",
  },
  {
    id: "ib_380",
    question: "Make the case for why precedent transactions are the most relevant valuation reference point when a company is in a formal sale process.",
    category: "Valuation",
    difficulty: "Medium",
  },

  // Hard
  {
    id: "ib_381",
    question: "How would you value a company with negative EBITDA?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_382",
    question: "How would you value a company with no earnings, no EBITDA, and minimal revenue — for example, a pre-revenue biotech or an early-stage platform business?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_383",
    question: "Explain how and why your choice of valuation methodology would change depending on the industry and the purpose of the analysis — M&A advisory vs. IPO vs. fairness opinion.",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_384",
    question: "A company has $100M EBITDA. Your trading comps yield 8–10x, precedent transactions yield 10–12x, and your DCF yields an implied EV of $750M. Why do these methods diverge and how do you reconcile them for a fairness opinion?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_385",
    question: "Walk me through a complete DCF: FCFF formula, WACC build, terminal value using both methods, and bridge to equity value per share. Assume $50M Year 5 FCF, 10% WACC, 2.5% terminal growth, $120M net debt, 40M diluted shares.",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_386",
    question: "Your DCF yields an implied EV/EBITDA of 18x, but your trading comps trade at 12x. What are the most likely explanations and how do you pressure-test your assumptions?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_387",
    question: "Walk through why a strategic acquirer can justify paying more for a target than a financial sponsor, including the structural reasons the IRR math works differently for each buyer type.",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_388",
    question: "Walk me through a sum-of-the-parts analysis for a conglomerate with four business units across different industries — when is it appropriate, how do you build it, and what is the conglomerate discount?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_389",
    question: "You're advising a board on a fairness opinion for a take-private bid at a 25% premium to the 30-day VWAP that is still below your DCF value. Walk through how you would present the analysis and frame your conclusion.",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_390",
    question: "Explain how terminal value can be derived from both the Gordon Growth Model and the Exit Multiple Method — and walk through the implicit assumptions each makes about the business at the end of the forecast period.",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_391",
    question: "A company's primary revenue source is a government contract expiring in 18 months with uncertain renewal prospects. How do you model terminal value and how does this risk change your discount rate?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_392",
    question: "A company has $100M EBITDA but $80M of it comes from a product facing patent expiry in 3 years. How do your DCF and comps analysis differ vs. a comparable without this risk?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_393",
    question: "Two companies have the same EV/EBITDA multiple but very different capital expenditure levels. Why is EV/EBITDA misleading here and what metric would you use instead?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_394",
    question: "A spinoff is trading at a significant discount to what a sum-of-the-parts analysis implies. Walk through the reasons a newly separated entity might trade at a discount immediately post-spin.",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_395",
    question: "Walk through how you would value an early-stage company with no revenue, no comparable transactions, and highly unpredictable cash flows. What frameworks exist and what are their limitations?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_396",
    question: "Why does using the Exit Multiple Method for terminal value sometimes produce circular logic, and how do practitioners address this problem?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_397",
    question: "Make the case for why terminal value is actually the most rigorously derived part of a DCF — push back on the conventional view that it is just a plug.",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_398",
    question: "How do you value a company that management is running materially below its potential, where normalized EBITDA under a new owner would be significantly higher than the reported figure?",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_399",
    question: "A company's peer group has leverage ratios ranging from 0x to 4x net debt/EBITDA. Walk through how you account for this dispersion when selecting and applying multiples, and why the median is insufficient.",
    category: "Valuation",
    difficulty: "Hard",
  },
  {
    id: "ib_400",
    question: "Walk me through how you would value a company in a sector with no public comparables and no precedent transactions in the past decade — what creative approaches can you use?",
    category: "Valuation",
    difficulty: "Hard",
  },
];

module.exports = { IB_QUESTIONS };
