import ReactMarkdown from "react-markdown";
import { useRouter } from "next/router";

const C = {
  bg: "#020817",
  surface: "#0d1b2e",
  surfaceHigh: "#132033",
  primary: "#1565C0",
  secondary: "#4FC3F7",
  text: "#e2e8f0",
  textMuted: "#64748b",
  border: "rgba(79,195,247,0.12)",
};

const content = `# Terms of Service

**Last updated: April 2026**

## 1. Acceptance of Terms

By accessing or using Fite Finance ("the Service") at fitefinance.com, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.

## 2. Description of Service

Fite Finance is an online finance interview preparation platform that provides AI-generated practice questions, model answers, and answer grading. The Service is intended for educational and practice purposes only and does not constitute professional financial, investment, or career advice.

## 3. Eligibility

You must be at least 18 years old to use this Service. By using the Service, you represent that you are at least 18 years of age.

## 4. Accounts

You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately at support@fitefinance.com if you suspect any unauthorized use of your account. We are not liable for any loss or damage arising from your failure to protect your account credentials.

## 5. Subscriptions and Payments

### Free Tier
Free users may access up to 5 questions per day with limited features.

### Premium Subscription
Premium access is available for $3/month (or the current price displayed at checkout). Premium subscribers receive unlimited questions, AI answer grading, question history, and additional features.

### Billing
Subscriptions are billed monthly on a recurring basis. By subscribing, you authorize us to charge your payment method on a recurring basis until you cancel. Payments are processed by Stripe. We do not store your payment information directly.

### Cancellation
You may cancel your subscription at any time through the customer portal accessible from your account. Cancellation takes effect at the end of the current billing period. You will retain access to premium features until the end of the paid period.

### Refunds
All purchases are final. We do not offer refunds for partial months or unused subscription time. If you believe you were charged in error, contact us at support@fitefinance.com within 7 days of the charge.

### Price Changes
We reserve the right to change subscription pricing at any time. We will provide reasonable notice of any price changes before they take effect.

## 6. Acceptable Use

You agree not to:
- Use the Service for any unlawful purpose
- Attempt to gain unauthorized access to any part of the Service
- Scrape, copy, or redistribute any content from the Service without permission
- Use automated tools or bots to access the Service
- Resell or commercially exploit the Service or its content
- Impersonate any person or entity
- Use the Service in any way that could damage, disable, or impair the Service

## 7. AI-Generated Content

All questions, answers, and feedback on Fite Finance are generated by artificial intelligence (OpenAI). By using the Service, you acknowledge that:

- AI-generated content may contain errors, inaccuracies, or outdated information
- The content is for practice purposes only and should not be relied upon as professional financial advice
- We make no guarantees about the accuracy, completeness, or suitability of any AI-generated content
- Interview questions and answers reflect general knowledge and may not reflect the practices of any specific employer

## 8. Intellectual Property

All content, design, code, and materials on Fite Finance are the property of Fite Finance and are protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works from any content on the Service without our explicit written permission.

## 9. Disclaimer of Warranties

THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE.

## 10. Limitation of Liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, FITE FINANCE AND ITS OWNERS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO:

- Loss of data or content
- Loss of revenue or profits
- Failure to obtain employment or achieve interview success
- Reliance on AI-generated content
- Service interruptions or downtime
- Unauthorized access to your account

OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM YOUR USE OF THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 3 MONTHS PRECEDING THE CLAIM.

## 11. Indemnification

You agree to indemnify and hold harmless Fite Finance and its owners from any claims, damages, losses, or expenses (including legal fees) arising from your use of the Service, your violation of these Terms, or your violation of any rights of a third party.

## 12. Third-Party Services

The Service uses the following third-party providers:
- **Clerk** — authentication and user management
- **Stripe** — payment processing
- **OpenAI** — AI content generation
- **Vercel** — hosting and infrastructure
- **Upstash** — data storage

Your use of the Service is also subject to the terms and privacy policies of these third-party providers. We are not responsible for the practices of these third parties.

## 13. Service Availability

We do not guarantee that the Service will be available at all times. We may suspend, discontinue, or modify the Service at any time without notice. We are not liable for any losses resulting from service interruptions or discontinuation.

## 14. Termination

We reserve the right to suspend or terminate your account at any time, with or without cause, including for violation of these Terms. Upon termination, your right to use the Service will immediately cease. If we terminate your account without cause, we will provide a prorated refund for any unused paid subscription time.

## 15. Governing Law

These Terms shall be governed by and construed in accordance with the laws of the United States. Any disputes arising from these Terms or your use of the Service shall be resolved through binding arbitration rather than in court, except that you may assert claims in small claims court.

## 16. Changes to Terms

We reserve the right to modify these Terms at any time. We will notify users of material changes by updating the "Last updated" date at the top of this page. Continued use of the Service after changes constitutes acceptance of the new Terms.

## 17. Contact

For questions about these Terms, contact us at support@fitefinance.com.`;

function TermsOfService() {
  const router = useRouter();
  return (
    <>
      <style jsx global>{`
        html, body { background: ${C.bg}; margin: 0; }
        .legal-content h1 { font-size: 26px; font-weight: 800; color: ${C.text}; margin: 0 0 6px; }
        .legal-content h2 { font-size: 16px; font-weight: 700; color: ${C.secondary}; margin: 28px 0 10px; text-transform: uppercase; letter-spacing: 0.06em; }
        .legal-content h3 { font-size: 14px; font-weight: 600; color: ${C.text}; margin: 20px 0 8px; }
        .legal-content p { font-size: 14px; color: ${C.textMuted}; line-height: 1.75; margin: 0 0 12px; }
        .legal-content ul { padding-left: 20px; margin: 0 0 12px; }
        .legal-content li { font-size: 14px; color: ${C.textMuted}; line-height: 1.75; margin-bottom: 4px; }
        .legal-content strong { color: ${C.text}; font-weight: 600; }
        .legal-content a { color: ${C.secondary}; text-decoration: none; }
        .legal-content a:hover { text-decoration: underline; }
      `}</style>
      <div style={{
        minHeight: "100vh",
        background: C.bg,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        fontFamily: "Inter, sans-serif",
      }}>
        {/* Top bar */}
        <div style={{
          width: "100%",
          maxWidth: 760,
          padding: "20px 24px 0",
          boxSizing: "border-box",
        }}>
          <button
            onClick={() => router.push("/")}
            style={{
              display: "flex",
              alignItems: "center",
              gap: 6,
              background: C.surfaceHigh,
              border: `1px solid ${C.border}`,
              borderRadius: 8,
              color: C.textMuted,
              fontSize: 13,
              fontWeight: 600,
              padding: "7px 14px",
              cursor: "pointer",
              fontFamily: "Inter, sans-serif",
              transition: "color 0.15s",
            }}
            onMouseEnter={e => e.currentTarget.style.color = C.text}
            onMouseLeave={e => e.currentTarget.style.color = C.textMuted}
          >
            ← Back
          </button>
        </div>

        {/* Content card */}
        <div style={{
          width: "100%",
          maxWidth: 760,
          margin: "24px 0 60px",
          padding: "0 24px",
          boxSizing: "border-box",
        }}>
          <div style={{
            background: C.surface,
            border: `1px solid ${C.border}`,
            borderRadius: 16,
            padding: "40px 44px",
          }}>
            <div className="legal-content">
              <ReactMarkdown>{content}</ReactMarkdown>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default TermsOfService;
